apiVersion: v1
kind: Secret

metadata:
  name: db-connection
type: Opaque

data:
  url: cG9zdGdyZXNxbDovL2RvYWRtaW46QVZOU19FUnZvTjY2LXJ1SHF1WnZlNHI0QG5sdy11bml0ZS1kby11c2VyLTE2MjQ3OTcyLTAuYy5kYi5vbmRpZ2l0YWxvY2Vhbi5jb206MjUwNjAvbnctdW5pdGU/c3NsbW9kZT1yZXF1aXJlCg==
